---
sudo: required
services: docker
language: generic

before_script:
  - sudo apt-get -y install qemu-user-static
  - sudo pip install tox
  - sudo -E docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
  - (cd .. && git clone https://github.com/estesp/manifest-tool)
  - (cd ../manifest-tool && git checkout v0.9.0)
  - (cd ../manifest-tool && sudo -E make && sudo -E make install)

jobs:
  include:
    - stage: run unit tests
      script: tox -e docs,pep8,pylint,yamllint,bashate,py27,cover
    - stage: build functest-core images
      script: sudo -E bash build.sh
      env:
        - REPO="${DOCKER_USERNAME}"
        - amd64_dirs="docker/core"
        - arm64_dirs=""
    - stage: publish functest-core manifests
      script: >
        sudo manifest-tool push from-args \
          --platforms linux/amd64 \
          --template ${DOCKER_USERNAME}/functest-core:ARCH-iruya \
          --target ${DOCKER_USERNAME}/functest-core:iruya
    - stage: build functest-tempest images
      script: sudo -E bash build.sh
      env:
        - REPO="${DOCKER_USERNAME}"
        - amd64_dirs="docker/tempest"
        - arm64_dirs=""
    - stage: publish functest-tempest manifests
      script: >
        sudo manifest-tool push from-args \
          --platforms linux/amd64 \
          --template ${DOCKER_USERNAME}/functest-tempest:ARCH-iruya \
          --target ${DOCKER_USERNAME}/functest-tempest:iruya
    - stage: build all functest images
      script: sudo -E bash build.sh
      env:
        - REPO="${DOCKER_USERNAME}"
        - amd64_dirs="docker/healthcheck"
        - arm64_dirs=""
    - script: sudo -E bash build.sh
      env:
        - REPO="${DOCKER_USERNAME}"
        - amd64_dirs="docker/smoke"
        - arm64_dirs=""
    - script: sudo -E bash build.sh
      env:
        - REPO="${DOCKER_USERNAME}"
        - amd64_dirs="docker/benchmarking"
        - arm64_dirs=""
    - script: sudo -E bash build.sh
      env:
        - REPO="${DOCKER_USERNAME}"
        - amd64_dirs="docker/features"
        - arm64_dirs=""
    - script: sudo -E bash build.sh
      env:
        - REPO="${DOCKER_USERNAME}"
        - amd64_dirs="docker/vnf"
        - arm64_dirs=""
    - stage: publish all manifests
      script: >
        sudo manifest-tool push from-args \
          --platforms linux/amd64 \
          --template ${DOCKER_USERNAME}/functest-healthcheck:ARCH-iruya \
          --target ${DOCKER_USERNAME}/functest-healthcheck:iruya
    - script: >
        sudo manifest-tool push from-args \
          --platforms linux/amd64 \
          --template ${DOCKER_USERNAME}/functest-smoke:ARCH-iruya \
          --target ${DOCKER_USERNAME}/functest-smoke:iruya
    - script: >
        sudo manifest-tool push from-args \
          --platforms linux/amd64 \
          --template ${DOCKER_USERNAME}/functest-features:ARCH-iruya \
          --target ${DOCKER_USERNAME}/functest-features:iruya
    - script: >
        sudo manifest-tool push from-args \
          --platforms linux/amd64 \
          --template ${DOCKER_USERNAME}/functest-vnf:ARCH-iruya \
          --target ${DOCKER_USERNAME}/functest-vnf:iruya
