---
- hosts: 127.0.0.1
  roles:
    - role: collivier.xtesting
      project: functest
      docker_args:
        env:
          DEPLOY_SCENARIO: os-nosdn-nofeature-noha
          NAMESERVER: 8.8.8.8
        volumes:
          - /home/opnfv/functest/openstack.creds:/home/opnfv/functest/conf/env_file
          - /home/opnfv/functest/images:/home/opnfv/functest/images
      suites:
        - repo: opnfv
          container: functest-healthcheck
          tag: hunter
          tests:
            - connection_check
            - tenantnetwork1
            - tenantnetwork2
            - vmready1
            - vmready2
            - singlevm1
            - singlevm2
            - vping_ssh
            - vping_userdata
            - cinder_test
            - odl
            - api_check
            - snaps_health_check
        - repo: opnfv
          container: functest-smoke
          tag: hunter
          tests:
            - tempest_smoke
            - neutron-tempest-plugin-api
            - rally_sanity
            - rally_jobs
            - refstack_defcore
            - patrole
            - snaps_smoke
            - neutron_trunk
            - networking-bgpvpn
            - networking-sfc
            - barbican
        - repo: opnfv
          container: functest-benchmarking
          tag: hunter
          tests:
            - vmtp
            - shaker
        - repo: opnfv
          container: functest-components
          tag: hunter
          tests:
            - tempest_full
            - tempest_scenario
            - rally_full
        - repo: opnfv
          container: functest-vnf
          tag: hunter
          tests:
            - cloudify
            - cloudify_ims
            - heat_ims
            - vyos_vrouter
            - juju_epc
        - repo: opnfv
          container: functest-features
          tag: hunter
          tests:
            - doctor-notification
            - bgpvpn
            - functest-odl-sfc
            - barometercollectd
            - fds
            - vgpu
            - stor4nfv_os
